/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_monicacastillo;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Monica
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        pb = new HiloProgressBar(ProgressBarHilo);
        pb.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreSerVivo = new javax.swing.JTextField();
        PoderSerVivo = new javax.swing.JFormattedTextField();
        AñosSerVivo = new javax.swing.JFormattedTextField();
        PlanetaSerVivo = new javax.swing.JTextField();
        RazaSerVivo = new javax.swing.JComboBox<>();
        AgregarSerVivo = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TreeSeresVivos = new javax.swing.JTree();
        jLabel12 = new javax.swing.JLabel();
        ProgressBarHilo = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ModificarAtributo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaSeresVivosModificar = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSeresVivosEliminar = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        EliminarSerVivo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        CBSeresVivos = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaDatosSeresVivos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        GuardarArchivo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaArchivo = new javax.swing.JTextArea();
        CargarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Agregar Ser Vivo");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Poder:");

        jLabel4.setText("Años:");

        jLabel5.setText("Planeta:");

        jLabel6.setText("Raza:");

        PoderSerVivo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AñosSerVivo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        RazaSerVivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));

        AgregarSerVivo.setText("Agregar Ser Vivo");
        AgregarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarSerVivoMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Seres Vivos");
        TreeSeresVivos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane6.setViewportView(TreeSeresVivos);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("JTree Seres Vivos");

        ProgressBarHilo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProgressBarHilo.setForeground(new java.awt.Color(255, 102, 51));
        ProgressBarHilo.setMaximum(1000);
        ProgressBarHilo.setString("");
        ProgressBarHilo.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlanetaSerVivo)
                    .addComponent(RazaSerVivo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PoderSerVivo)
                    .addComponent(AñosSerVivo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(AgregarSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProgressBarHilo, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NombreSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PoderSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(AñosSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PlanetaSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RazaSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AgregarSerVivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProgressBarHilo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar Ser Vivo", jPanel1);

        jLabel7.setText("Modificar Ser Vivo");

        ModificarAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Poder", "Años", "Planeta de procedencia", "Raza" }));
        ModificarAtributo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ModificarAtributoItemStateChanged(evt);
            }
        });

        TablaSeresVivosModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Poder", "Años", "Planeta ", "Raza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaSeresVivosModificar);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("* Seleccione una fila para poder modificar un atributo *");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(ModificarAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(ModificarAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Ser Vivo", jPanel2);

        TablaSeresVivosEliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Poder", "Años", "Planeta", "Raza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaSeresVivosEliminar);

        jLabel8.setText("Eliminar Ser Vivo");

        EliminarSerVivo.setText("Eliminar Ser Vivo");
        EliminarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarSerVivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(EliminarSerVivo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(EliminarSerVivo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar Ser Vivo", jPanel3);

        CBSeresVivos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBSeresVivosItemStateChanged(evt);
            }
        });

        TablaDatosSeresVivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Poder", "Años", "Planeta", "Raza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TablaDatosSeresVivos);

        jLabel10.setText("Seres Vivos");

        GuardarArchivo.setText("Guardar Archivo");
        GuardarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(GuardarArchivo))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(CBSeresVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBSeresVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuardarArchivo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Guardar Archivo", jPanel6);

        TextAreaArchivo.setColumns(20);
        TextAreaArchivo.setRows(5);
        jScrollPane3.setViewportView(TextAreaArchivo);

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(CargarArchivo)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(CargarArchivo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Abrir Archivo", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarArchivoMouseClicked
        // TODO add your handling code here:
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        TextAreaArchivo.setText("");
        try {
            JFileChooser filechooser = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
            filechooser.setFileFilter(filtro);
            int seleccion = filechooser.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                selectedFile = filechooser.getSelectedFile();
                fichero = filechooser.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                TextAreaArchivo.setText("");
                while ((linea = br.readLine()) != null) {
                    TextAreaArchivo.append(linea);
                    TextAreaArchivo.append("\n");
                } // Fin While
            } // Fin If 
        } catch (Exception e) {
            e.printStackTrace();
        } // Fin Try Catch
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
        } // Fin Try Catch
    }//GEN-LAST:event_CargarArchivoMouseClicked

    private void EliminarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarSerVivoMouseClicked
        // TODO add your handling code here:
        try {
            if (TablaSeresVivosEliminar.getSelectedRow() >= 0) {
                int pos = TablaSeresVivosEliminar.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) TablaSeresVivosEliminar.getModel();
                modelo.removeRow(TablaSeresVivosEliminar.getSelectedRow());
                TablaSeresVivosEliminar.setModel(modelo);
                TablaSeresVivosModificar.setModel(modelo);
                DefaultComboBoxModel cb = (DefaultComboBoxModel) CBSeresVivos.getModel();
                Universo uni = new Universo(selectedFile.getPath());
                uni.CargarArchivo2();
                uni.EliminarElemento(((SerVivo) cb.getElementAt(pos)).getNombre());
                cb.removeElementAt(pos);
                CBSeresVivos.setModel(cb);
                JOptionPane.showMessageDialog(null, "Se elimino con exito");
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_EliminarSerVivoMouseClicked

    private void ModificarAtributoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ModificarAtributoItemStateChanged
        // TODO add your handling code here:
        try {
            String nombre, planeta, raza;
            int poder, años;
            switch (ModificarAtributo.getSelectedIndex()) {
                case 0:
                    if (TablaSeresVivosModificar.getSelectedRow() >= 0) {
                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        DefaultTableModel modelo = (DefaultTableModel) TablaSeresVivosModificar.getModel();
                        nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                        modelo.setValueAt(nombre, TablaSeresVivosModificar.getSelectedRow(), 0);
                        TablaSeresVivosModificar.setModel(modelo);
                        TablaSeresVivosEliminar.setModel(modelo);
                        DefaultComboBoxModel cb = (DefaultComboBoxModel) CBSeresVivos.getModel();
                        ((SerVivo) cb.getElementAt(pos)).setNombre(nombre);
                        CBSeresVivos.setModel(cb);
//                        Universo uni = new Universo(selectedFile.getPath());
//                        uni.CargarArchivo(TextAreaArchivo);
//                        int pos = TablaSeresVivosModificar.getSelectedRow();
//                        uni.getSeresvivos().get(pos).setNombre(nombre);
//                        uni.EscribirArchivo();
                    } // Fin If
                    break;
                case 1:
                    if (TablaSeresVivosModificar.getSelectedRow() >= 0) {
                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        DefaultTableModel modelo1 = (DefaultTableModel) TablaSeresVivosModificar.getModel();
                        poder = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el nuevo poder: "));
                        modelo1.setValueAt(poder, TablaSeresVivosModificar.getSelectedRow(), 1);
                        TablaSeresVivosModificar.setModel(modelo1);
                        TablaSeresVivosEliminar.setModel(modelo1);
                        DefaultComboBoxModel cb = (DefaultComboBoxModel) CBSeresVivos.getModel();
                        ((SerVivo) cb.getElementAt(pos)).setPoder(poder);
                        CBSeresVivos.setModel(cb);
//                        Universo uni = new Universo(selectedFile.getPath());
//                        uni.CargarArchivo(TextAreaArchivo);
//                        int pos = TablaSeresVivosModificar.getSelectedRow();
//                        uni.getSeresvivos().get(pos).setPoder(poder);
//                        uni.EscribirArchivo();
                    } // Fin If
                    break;
                case 2:
                    if (TablaSeresVivosModificar.getSelectedRow() >= 0) {
                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        DefaultTableModel modelo2 = (DefaultTableModel) TablaSeresVivosModificar.getModel();
                        años = Integer.parseInt(JOptionPane.showInputDialog("Ingrese los nuevos años: "));
                        modelo2.setValueAt(años, TablaSeresVivosModificar.getSelectedRow(), 2);
                        TablaSeresVivosModificar.setModel(modelo2);
                        TablaSeresVivosEliminar.setModel(modelo2);
                        DefaultComboBoxModel cb = (DefaultComboBoxModel) CBSeresVivos.getModel();
                        ((SerVivo) cb.getElementAt(pos)).setAños(años);
                        CBSeresVivos.setModel(cb);
//                        Universo uni = new Universo(selectedFile.getPath());
//                        uni.CargarArchivo(TextAreaArchivo);
//                        int pos = TablaSeresVivosModificar.getSelectedRow();
//                        uni.getSeresvivos().get(pos).setAños(años);
//                        uni.EscribirArchivo();
                    } // Fin If
                    break;
                case 3:
                    if (TablaSeresVivosModificar.getSelectedRow() >= 0) {
                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        DefaultTableModel modelo3 = (DefaultTableModel) TablaSeresVivosModificar.getModel();
                        planeta = JOptionPane.showInputDialog("Ingrese el nuevo planeta: ");
                        modelo3.setValueAt(planeta, TablaSeresVivosModificar.getSelectedRow(), 3);
                        TablaSeresVivosModificar.setModel(modelo3);
                        TablaSeresVivosEliminar.setModel(modelo3);
                        DefaultComboBoxModel cb = (DefaultComboBoxModel) CBSeresVivos.getModel();
                        ((SerVivo) cb.getElementAt(pos)).setPlaneta(planeta);
                        CBSeresVivos.setModel(cb);
//                        Universo uni = new Universo(selectedFile.getPath());
//                        uni.CargarArchivo(TextAreaArchivo);
//                        int pos = TablaSeresVivosModificar.getSelectedRow();
//                        uni.getSeresvivos().get(pos).setPlaneta(planeta);
//                        uni.EscribirArchivo()
                    } // Fin If
                    break;
                case 4:
                    if (TablaSeresVivosModificar.getSelectedRow() >= 0) {
                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        DefaultTableModel modelo4 = (DefaultTableModel) TablaSeresVivosModificar.getModel();
                        int opcion = Integer.parseInt(JOptionPane.showInputDialog("1. Humano" + "\n" + "2. Amanto" + "\n" + "Ingrese la nueva raza: "));
                        switch (opcion) {
                            case 1:
                                raza = "Humano";
                                modelo4.setValueAt(raza, TablaSeresVivosModificar.getSelectedRow(), 4);
                                TablaSeresVivosModificar.setModel(modelo4);
                                TablaSeresVivosEliminar.setModel(modelo4);
                                DefaultComboBoxModel cb = (DefaultComboBoxModel) CBSeresVivos.getModel();
                                ((SerVivo) cb.getElementAt(pos)).setRaza(raza);
                                CBSeresVivos.setModel(cb);
//                        Universo uni = new Universo(selectedFile.getPath());
//                        uni.CargarArchivo(TextAreaArchivo);
//                        int pos = TablaSeresVivosModificar.getSelectedRow();
//                        uni.getSeresvivos().get(pos).setRaza(raza);
//                        uni.EscribirArchivo()
                                break;
                            case 2:
                                raza = "Amanto";
                                modelo4.setValueAt(raza, TablaSeresVivosModificar.getSelectedRow(), 4);
                                TablaSeresVivosModificar.setModel(modelo4);
                                TablaSeresVivosEliminar.setModel(modelo4);
                                DefaultComboBoxModel cb1 = (DefaultComboBoxModel) CBSeresVivos.getModel();
                                ((SerVivo) cb1.getElementAt(pos)).setRaza(raza);
                                CBSeresVivos.setModel(cb1);
//                        Universo uni = new Universo(selectedFile.getPath());
//                        uni.CargarArchivo(TextAreaArchivo);
//                        int pos = TablaSeresVivosModificar.getSelectedRow();
//                        uni.getSeresvivos().get(pos).setRaza(raza);
//                        uni.EscribirArchivo()
                                break;
                            default:
                                JOptionPane.showMessageDialog(this, "Opcion no valida");
                        } // Fin Switch
                    } // Fin If
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Ocurrio un error y no se pudo modificar");
            } // Fin Switch
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_ModificarAtributoItemStateChanged

    private void AgregarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarSerVivoMouseClicked
        // TODO add your handling code here:
        String nombre, planeta, raza;
        int poder, años;
        try {
            // Agrego un Ser Vivo a el ArrayList
            nombre = NombreSerVivo.getText();
            poder = Integer.parseInt(PoderSerVivo.getText());
            años = Integer.parseInt(AñosSerVivo.getText());
            planeta = PlanetaSerVivo.getText();
            raza = RazaSerVivo.getSelectedItem().toString();
            if (poder >= 1 && poder <= 10) {
                SerVivo sv = new SerVivo(nombre, poder, años, planeta, raza);
                Object[] newrow = {nombre, poder, años, planeta, raza};
                DefaultTableModel modelo = (DefaultTableModel) TablaSeresVivosEliminar.getModel();
                modelo.addRow(newrow);
                TablaSeresVivosEliminar.setModel(modelo);
                TablaSeresVivosModificar.setModel(modelo);
                DefaultComboBoxModel cb = (DefaultComboBoxModel) CBSeresVivos.getModel();
                cb.addElement(sv);
                CBSeresVivos.setModel(cb);
//                uni.getSeresvivos().add(sv);

                JOptionPane.showMessageDialog(this, "Ser vivo agregado exitosamente");
                DefaultTreeModel m = (DefaultTreeModel) TreeSeresVivos.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultMutableTreeNode nodoSerVivo;
                nodoSerVivo = new DefaultMutableTreeNode(sv);
                DefaultMutableTreeNode nodoPoder;
                nodoPoder = new DefaultMutableTreeNode("Poder: " + sv.getPoder());
                DefaultMutableTreeNode nodoPlaneta;
                nodoPlaneta = new DefaultMutableTreeNode(sv.getPlaneta());
                DefaultMutableTreeNode nodoEdad;
                nodoEdad = new DefaultMutableTreeNode("Edad: " + sv.getAños());
                DefaultMutableTreeNode nodoRaza;
                nodoRaza = new DefaultMutableTreeNode(sv.getRaza());
                nodoRaza.add(nodoEdad);
                nodoRaza.add(nodoPoder);
                nodoPlaneta.add(nodoRaza);
                nodoSerVivo.add(nodoPlaneta);
                raiz.add(nodoSerVivo);
                m.reload();
                NombreSerVivo.setText("");
                PoderSerVivo.setText("");
                AñosSerVivo.setText("");
                PlanetaSerVivo.setText("");
                RazaSerVivo.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "¡El poder debe ser de 1 a 10!");
                NombreSerVivo.setText("");
                PoderSerVivo.setText("");
                AñosSerVivo.setText("");
                PlanetaSerVivo.setText("");
                RazaSerVivo.setSelectedIndex(0);
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_AgregarSerVivoMouseClicked

    private void GuardarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarArchivoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modeloy = (DefaultTableModel) TablaDatosSeresVivos.getModel();
        if (modeloy.getRowCount() != 0) {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showSaveDialog(this);
            FileWriter fw = null;
            BufferedWriter bw = null;
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                try {
                    if (jfc.getFileFilter().getDescription().equals("Archivo de Texto")) {
                        selectedFile = new File(jfc.getSelectedFile().getPath() + ".txt");
                    } else {
                        selectedFile = jfc.getSelectedFile();
                    } // Fin If
                    fw = new FileWriter(selectedFile);
                    bw = new BufferedWriter(fw);
                    DefaultTableModel modelo = (DefaultTableModel) TablaDatosSeresVivos.getModel();
                    String acum = "";
                    for (int i = 0; i < modelo.getRowCount(); i++) {
                        for (int j = 0; j < modelo.getColumnCount(); j++) {
                            if (j == modelo.getColumnCount() - 1) {
                                acum += modelo.getValueAt(i, j);
                            } else {
                                acum += modelo.getValueAt(i, j) + "|";
                            } // Fin If
                        } // Fin For
                        acum += "\n";
                    } // Fin For
                    bw.write(acum);
                    bw.flush();
                    JOptionPane.showMessageDialog(this, "¡Se ha guardado exitosamente el archivo!");
                } catch (Exception e) {
                    e.printStackTrace();
                } // Fin Try Catch
                try {
                    bw.close();
                    fw.close();
                } catch (IOException io) {
                    io.printStackTrace();
                } // Fin Try Catch
            } // Fin If
        } else {
            JOptionPane.showMessageDialog(this, "¡La tabla debe tener por lo menos 1 ser vivo!");
        } // Fin If
    }//GEN-LAST:event_GuardarArchivoMouseClicked

    private void CBSeresVivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBSeresVivosItemStateChanged
        // TODO add your handling code here:
        try {
            if (evt.getStateChange() == 2) {
                SerVivo sv = (SerVivo) CBSeresVivos.getSelectedItem();
                Object[] newrow = {sv.getNombre(), sv.getPoder(), sv.getAños(), sv.getPlaneta(), sv.getRaza()};
                DefaultTableModel modelo = (DefaultTableModel) TablaDatosSeresVivos.getModel();
                modelo.addRow(newrow);
                TablaDatosSeresVivos.setModel(modelo);
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se mostraron los datos");
        } // Fin Try Catch

    }//GEN-LAST:event_CBSeresVivosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarSerVivo;
    private javax.swing.JFormattedTextField AñosSerVivo;
    private javax.swing.JComboBox<String> CBSeresVivos;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton EliminarSerVivo;
    private javax.swing.JButton GuardarArchivo;
    private javax.swing.JComboBox<String> ModificarAtributo;
    private javax.swing.JTextField NombreSerVivo;
    private javax.swing.JTextField PlanetaSerVivo;
    private javax.swing.JFormattedTextField PoderSerVivo;
    private javax.swing.JProgressBar ProgressBarHilo;
    private javax.swing.JComboBox<String> RazaSerVivo;
    private javax.swing.JTable TablaDatosSeresVivos;
    private javax.swing.JTable TablaSeresVivosEliminar;
    private javax.swing.JTable TablaSeresVivosModificar;
    private javax.swing.JTextArea TextAreaArchivo;
    private javax.swing.JTree TreeSeresVivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
Universo uni = new Universo();
    File selectedFile = null;
    HiloProgressBar pb;

}
